### ISSUE TITLE
Error in script

### ISSUE THREAD

**Issue by cmuell89** [etpr/sequential-manifold-planning#1]
Hey ETPR,

Really cool work here! I am working on a similar problem but through the lens of human provided demonstration. I wanted to try out your code but I get an error right away when running run_smp.py:

```{'SEED': 1, 'CONV_TOL': 0.1, 'N': 2000, 'ALPHA': 0.5, 'BETA': 0.05, 'COLLISION_RES': 0.1, 'EPS': 0.01, 'RHO': 0.1, 'R_MAX': 1.5, 'GREEDY': False, 'PROJ_STEP_SIZE': 1.0}
number of nodes in tree_0 = 1219
number of goal nodes in tree_0 = 88
Traceback (most recent call last):
  File "run_smp.py", line 24, in <module>
    path_idx, path = planner.run()
  File "/home/carlmueller/cairo/sequential-manifold-planning/smp/smp.py", line 62, in run
    next_manifold=self.task.manifolds[n+1])
  File "/home/carlmueller/cairo/sequential-manifold-planning/smp/smp.py", line 190, in grow_tree
    q_near, q_near_id = self.G.get_nearest_neighbor(node_value=q_target)
  File "/home/carlmueller/cairo/sequential-manifold-planning/smp/tree.py", line 74, in get_nearest_neighbor
    self.update_kd_tree()
  File "/home/carlmueller/cairo/sequential-manifold-planning/smp/tree.py", line 67, in update_kd_tree
    self.kd_tree = cKDTree(data)
  File "sklearn/neighbors/_binary_tree.pxi", line 1052, in sklearn.neighbors._kd_tree.BinaryTree.__init__
  File "/home/carlmueller/cairo/sequential-manifold-planning/env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/carlmueller/cairo/sequential-manifold-planning/env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 664, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/carlmueller/cairo/sequential-manifold-planning/env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
````

It looks like some errant value is being passed into the KDTree withing the data variable...

Cheers,
Carl

**Comment by etpr** [comment]
Hi Carl,
Thanks for posting this issue. I could reproduce it on my machine and it seems that newer versions of scikit-learn led to this issue. I'm working on a solution right now because I also want to use it in future projects. A brief fix for now should be to run it with an older scikit-learn version, for example 'scikit-learn==0.21.2'.
Best,
Peter

**Comment by cmuell89** [comment]
Worked like a charm. The plotting visuals are fantastic. Is your group open to me using your software in my own research, properly cited of course?

**Comment by etpr** [comment]
sorry for the late response. Sure, feel free to use the software for you research.
I also just did a major revision of the code.
